version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - ./data/postgres/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - '.env'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - '.env'
 
